
name: Build & Push JMeter Docker

on:
  push:
    branches: [ main ]

env:
  DOCKERHUB_USERNAME: sazhnovperformance
  IMAGE_NAME: jmeter-cloud

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Read standard plugins list
        id: plugins
        run: echo "JMETER_PLUGINS=$(paste -sd, plugins.txt)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image with plugins baked in
        run: |
          docker build             --build-arg JMETER_PLUGINS=${{ env.JMETER_PLUGINS }}             -t $DOCKERHUB_USERNAME/$IMAGE_NAME:5.6.3 .

      - name: Push to Docker Hub
        run: docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:5.6.3
